version: "3"

services:
  node:
    build: .
    user: node
    container_name: quimica_na_tela
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./src/:/app/src
      - ./__tests__/coverage/:/app/__tests__/coverage
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3001
      NODE_ENV: 'development'
    networks:
      - quimica_na_tela_net

  db:
    container_name: quimica_na_tela_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - quimica_na_tela_net

networks:
  quimica_na_tela_net:
    driver: bridge

# As chaves `tty`, `stdin_open` e `command` fazem com que o container fique
# rodando em segundo plano, bem como tornam possível o uso do comando
# `docker attach`, já deixando o terminal atual acoplado ao container, direto
# no bash. Apesar disso, utilizar o attach mais de uma vez irá replicar o
# terminal, portanto é melhor utilizar o comando `docker exec`.
